-- ==============================================================================
-- AssociaGo — MySQL baseline schema (profilo cloud)
--
-- Generato da Hibernate dalle 57 entity JPA (dialetto MySQL 8) e validato su
-- MySQL 8.4. Rappresenta l'intero schema usato dall'applicazione: qualsiasi
-- futura modifica va aggiunta come nuova migrazione V2, V3, ... in questa cartella.
--
-- NB: le migrazioni SQLite restano in classpath:db/migration (profilo desktop).
-- ==============================================================================

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `accounts` (
  `balance` decimal(38,2) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `parent_account_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` enum('ASSET','EQUITY','EXPENSE','LIABILITY','REVENUE') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `activities` (
  `cancellation_date` date DEFAULT NULL,
  `cost` decimal(38,2) NOT NULL,
  `end_date` date DEFAULT NULL,
  `end_time` time(6) DEFAULT NULL,
  `generate_invoice` bit(1) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `max_participants` int DEFAULT NULL,
  `require_registration` bit(1) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `start_time` time(6) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `cancellation_reason` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `description` text,
  `document_path` varchar(255) DEFAULT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `schedule_details` varchar(255) DEFAULT NULL,
  `subscription_type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `activity_costs` (
  `amount` decimal(38,2) NOT NULL,
  `incurred_date` date NOT NULL,
  `is_recurring` bit(1) DEFAULT NULL,
  `activity_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `category` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `frequency` varchar(255) DEFAULT NULL,
  `notes` text,
  `receipt_path` varchar(255) DEFAULT NULL,
  `supplier` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `activity_instructors` (
  `compensation` decimal(38,2) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `activity_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_association_id` bigint DEFAULT NULL,
  `certifications` varchar(255) DEFAULT NULL,
  `compensation_type` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `notes` text,
  `phone` varchar(255) DEFAULT NULL,
  `specialization` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `activity_participants` (
  `amount_paid` decimal(38,2) DEFAULT NULL,
  `cancellation_date` date DEFAULT NULL,
  `discount_amount` decimal(38,2) DEFAULT NULL,
  `expiration_date` date DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `is_paid` bit(1) DEFAULT NULL,
  `original_amount` decimal(38,2) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `registration_date` date NOT NULL,
  `activity_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `invoice_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `cancellation_reason` varchar(255) DEFAULT NULL,
  `coupon_code` varchar(255) DEFAULT NULL,
  `discount_type` varchar(255) DEFAULT NULL,
  `notes` text,
  `payment_method` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKa4o5fsnjt8sc9n6oq4fvxlreq` (`user_id`),
  CONSTRAINT `FKa4o5fsnjt8sc9n6oq4fvxlreq` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `activity_schedules` (
  `day_of_week` int NOT NULL,
  `end_time` time(6) NOT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `start_time` time(6) NOT NULL,
  `activity_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `instructor_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `annual_balance_lines` (
  `amount` decimal(38,2) DEFAULT NULL,
  `is_subtotal` bit(1) DEFAULT NULL,
  `previous_year_amount` decimal(38,2) DEFAULT NULL,
  `sort_order` int DEFAULT NULL,
  `variance` decimal(38,2) DEFAULT NULL,
  `variance_pct` decimal(38,2) DEFAULT NULL,
  `balance_id` bigint NOT NULL,
  `category_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `label` varchar(255) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `section` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `annual_balances` (
  `closing_fund` decimal(38,2) DEFAULT NULL,
  `net_result` decimal(38,2) DEFAULT NULL,
  `opening_fund` decimal(38,2) DEFAULT NULL,
  `total_expenses` decimal(38,2) DEFAULT NULL,
  `total_income` decimal(38,2) DEFAULT NULL,
  `year` int NOT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `computed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `checksum` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `pdf_path` varchar(255) DEFAULT NULL,
  `signatories` text,
  `status` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKqwmpkjjmtambda7g26j969n5k` (`association_id`,`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `assemblies` (
  `first_call_quorum` double DEFAULT NULL,
  `is_quorum_reached` bit(1) DEFAULT NULL,
  `second_call_quorum` double DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `date` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `end_time` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `minutes_path` varchar(255) DEFAULT NULL,
  `notes` text,
  `president` varchar(255) DEFAULT NULL,
  `secretary` varchar(255) DEFAULT NULL,
  `start_time` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `assembly_documents` (
  `is_mandatory` bit(1) DEFAULT NULL,
  `assembly_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `file_path` varchar(255) NOT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `assembly_motions` (
  `is_approved` bit(1) DEFAULT NULL,
  `is_planned` bit(1) DEFAULT NULL,
  `order_number` int DEFAULT NULL,
  `valid_votes` int DEFAULT NULL,
  `votes_abstain` int DEFAULT NULL,
  `votes_against` int DEFAULT NULL,
  `votes_in_favor` int DEFAULT NULL,
  `assembly_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `decision_summary` text,
  `decision_taken` varchar(255) DEFAULT NULL,
  `description` text,
  `notes` text,
  `title` varchar(255) NOT NULL,
  `voting_type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `assembly_participants` (
  `assembly_id` bigint NOT NULL,
  `check_in_time` datetime(6) DEFAULT NULL,
  `check_out_time` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `proxy_receiver_id` bigint DEFAULT NULL,
  `user_association_id` bigint NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `participation_type` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `assembly_votes` (
  `assembly_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `motion_id` bigint NOT NULL,
  `user_association_id` bigint NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `vote` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `association_deadlines` (
  `due_date` date NOT NULL,
  `recurring` bit(1) NOT NULL,
  `recurring_months` int DEFAULT NULL,
  `reminder_days` int DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `completed_by` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `description` text,
  `status` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `association_documents` (
  `version` int DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `uploaded_by` bigint DEFAULT NULL,
  `document_type` varchar(255) NOT NULL,
  `file_path` varchar(255) NOT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `association_locations` (
  `is_primary` bit(1) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `location_type` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `notes` text,
  `phone` varchar(255) DEFAULT NULL,
  `postal_code` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `associations` (
  `base_membership_fee` double DEFAULT NULL,
  `db_port` int DEFAULT NULL,
  `db_ssl` bit(1) DEFAULT NULL,
  `foundation_date` date DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `use_remote_db` bit(1) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `federation_registered_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `db_host` varchar(255) DEFAULT NULL,
  `db_name` varchar(255) DEFAULT NULL,
  `db_password` varchar(255) DEFAULT NULL,
  `db_type` varchar(255) DEFAULT NULL,
  `db_user` varchar(255) DEFAULT NULL,
  `description` text,
  `email` varchar(255) NOT NULL,
  `federation_provider` varchar(255) DEFAULT NULL,
  `federation_registration_number` varchar(255) DEFAULT NULL,
  `membership_number_format` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `partner_logo_path` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `president` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  `regulation_path` varchar(255) DEFAULT NULL,
  `secondary_logo_path` varchar(255) DEFAULT NULL,
  `secretary` varchar(255) DEFAULT NULL,
  `slug` varchar(255) NOT NULL,
  `statute_path` varchar(255) DEFAULT NULL,
  `tax_code` varchar(255) DEFAULT NULL,
  `treasurer` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `vat_number` varchar(255) DEFAULT NULL,
  `vice_president` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `logo` varbinary(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `attendance_records` (
  `check_in_time` time(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint DEFAULT NULL,
  `session_id` bigint DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `attendance_sessions` (
  `date` date DEFAULT NULL,
  `end_time` time(6) DEFAULT NULL,
  `start_time` time(6) DEFAULT NULL,
  `activity_id` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `instructor_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `audit_log` (
  `association_id` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `entity_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint DEFAULT NULL,
  `action` varchar(255) NOT NULL,
  `description` text,
  `entity_type` varchar(255) NOT NULL,
  `ip_address` varchar(255) DEFAULT NULL,
  `new_value` text,
  `old_value` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `budget_lines` (
  `actual_amount` decimal(38,2) DEFAULT NULL,
  `budgeted_amount` decimal(38,2) NOT NULL,
  `forecast_amount` decimal(38,2) DEFAULT NULL,
  `sort_order` int DEFAULT NULL,
  `budget_id` bigint NOT NULL,
  `category_id` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `label` varchar(255) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `budgets` (
  `year` int NOT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKbfjbuw7w1ttfghviboq65xnnm` (`association_id`,`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `cash_register_entries` (
  `amount` decimal(38,2) NOT NULL,
  `cash_register_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `time` datetime(6) DEFAULT NULL,
  `transaction_id` bigint DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `receipt_number` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `cash_registers` (
  `closing_balance` decimal(38,2) DEFAULT NULL,
  `date` date NOT NULL,
  `opening_balance` decimal(38,2) NOT NULL,
  `total_expense` decimal(38,2) DEFAULT NULL,
  `total_income` decimal(38,2) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `closed_at` datetime(6) DEFAULT NULL,
  `closed_by` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `opened_at` datetime(6) DEFAULT NULL,
  `opened_by` bigint NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKdsuy2mp89ihd66ybb5jgls61s` (`association_id`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `certificate_templates` (
  `is_active` bit(1) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `background_image_path` varchar(255) DEFAULT NULL,
  `body_html` text NOT NULL,
  `footer_image_path` varchar(255) DEFAULT NULL,
  `header_image_path` varchar(255) DEFAULT NULL,
  `merge_fields` text,
  `name` varchar(255) NOT NULL,
  `orientation` varchar(255) DEFAULT NULL,
  `paper_size` varchar(255) DEFAULT NULL,
  `signatory_roles` text,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `communication_recipients` (
  `communication_id` bigint NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sent_at` datetime(6) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `error_message` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `communication_templates` (
  `is_active` bit(1) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `body_html` text NOT NULL,
  `body_text` text,
  `category` varchar(255) DEFAULT NULL,
  `language` varchar(255) DEFAULT NULL,
  `merge_fields` text,
  `name` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `communications` (
  `delivered_count` int DEFAULT NULL,
  `failed_count` int DEFAULT NULL,
  `total_recipients` int DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `scheduled_at` datetime(6) DEFAULT NULL,
  `sent_at` datetime(6) DEFAULT NULL,
  `sent_by` bigint DEFAULT NULL,
  `template_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `body_html` text NOT NULL,
  `body_text` text,
  `channel` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `segment_filter` text,
  `sender_email` varchar(255) DEFAULT NULL,
  `sender_name` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `coupon_activities` (
  `activity_id` bigint NOT NULL,
  `coupon_id` bigint NOT NULL,
  PRIMARY KEY (`activity_id`,`coupon_id`),
  KEY `FKm3fvevkp5576vnc7xt7lhwk8w` (`coupon_id`),
  CONSTRAINT `FKh7deqffh2uy1xbsp6kh42ql17` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`),
  CONSTRAINT `FKm3fvevkp5576vnc7xt7lhwk8w` FOREIGN KEY (`coupon_id`) REFERENCES `coupons` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `coupon_events` (
  `coupon_id` bigint NOT NULL,
  `event_id` bigint NOT NULL,
  PRIMARY KEY (`coupon_id`,`event_id`),
  KEY `FKn2shhjibtt9us3mv10btgq67g` (`event_id`),
  CONSTRAINT `FKn2shhjibtt9us3mv10btgq67g` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`),
  CONSTRAINT `FKrokl5ek41xwjx3d9cnwmpg6v3` FOREIGN KEY (`coupon_id`) REFERENCES `coupons` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `coupons` (
  `current_uses` int DEFAULT NULL,
  `discount_value` decimal(38,2) NOT NULL,
  `end_date` date DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `max_uses` int DEFAULT NULL,
  `min_amount` decimal(38,2) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `discount_type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `event_participants` (
  `amount_paid` decimal(38,2) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `check_in_time` datetime(6) DEFAULT NULL,
  `event_id` bigint NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `invoice_id` bigint DEFAULT NULL,
  `registration_date` datetime(6) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `guest_email` varchar(255) DEFAULT NULL,
  `guest_name` varchar(255) DEFAULT NULL,
  `notes` text,
  `payment_method` varchar(255) DEFAULT NULL,
  `payment_status` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK2x391urx4up03f4jp2y9mdt5x` (`event_id`),
  KEY `FKre6m0d4mgt4351tytlkac9jvf` (`user_id`),
  CONSTRAINT `FK2x391urx4up03f4jp2y9mdt5x` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`),
  CONSTRAINT `FKre6m0d4mgt4351tytlkac9jvf` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `events` (
  `cost_member` decimal(38,2) DEFAULT NULL,
  `cost_non_member` decimal(38,2) DEFAULT NULL,
  `generate_invoice` bit(1) DEFAULT NULL,
  `is_public` bit(1) DEFAULT NULL,
  `max_participants` int DEFAULT NULL,
  `require_registration` bit(1) DEFAULT NULL,
  `association_id` bigint DEFAULT NULL,
  `cancellation_date` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `end_datetime` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `start_datetime` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `cancellation_reason` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `fiscal_comparisons` (
  `base_year` int NOT NULL,
  `comparison_year` int NOT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `generated_at` datetime(6) DEFAULT NULL,
  `generated_by` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `checksum` varchar(255) DEFAULT NULL,
  `csv_path` varchar(255) DEFAULT NULL,
  `data_snapshot` text,
  `pdf_path` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `fiscal_year_closures` (
  `members_count` int DEFAULT NULL,
  `net_balance` decimal(38,2) DEFAULT NULL,
  `total_expenses` decimal(38,2) DEFAULT NULL,
  `total_income` decimal(38,2) DEFAULT NULL,
  `year` int NOT NULL,
  `association_id` bigint NOT NULL,
  `closed_at` datetime(6) DEFAULT NULL,
  `closed_by` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `notes` text,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `import_logs` (
  `error_rows` int DEFAULT NULL,
  `imported_rows` int DEFAULT NULL,
  `skipped_rows` int DEFAULT NULL,
  `total_rows` int DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `imported_by` bigint DEFAULT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `entity_type` varchar(255) NOT NULL,
  `errors_detail` text,
  `file_checksum` varchar(255) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `institutional_signatures` (
  `is_active` bit(1) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `signature_mime_type` varchar(255) DEFAULT NULL,
  `signer_name` varchar(255) NOT NULL,
  `signer_role` varchar(255) NOT NULL,
  `signer_title` varchar(255) DEFAULT NULL,
  `signature_image` varbinary(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK8h0fq5eyj9x97s2slnx6uipil` (`association_id`,`signer_role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `inventory_items` (
  `current_value` decimal(38,2) DEFAULT NULL,
  `depreciation_years` int DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  `purchase_price` decimal(38,2) DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `assigned_to` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `acquisition_method` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `condition_status` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `inventory_code` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `notes` text,
  `photo_path` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `inventory_loans` (
  `actual_return_date` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `expected_return_date` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `item_id` bigint NOT NULL,
  `loan_date` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_association_id` bigint NOT NULL,
  `condition_on_loan` varchar(255) DEFAULT NULL,
  `condition_on_return` varchar(255) DEFAULT NULL,
  `notes` text,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `invoice_checks` (
  `numbering_ok` bit(1) DEFAULT NULL,
  `overdue_amount` decimal(38,2) DEFAULT NULL,
  `overdue_count` int DEFAULT NULL,
  `payment_ok` bit(1) DEFAULT NULL,
  `total_amount` decimal(38,2) DEFAULT NULL,
  `total_collected` decimal(38,2) DEFAULT NULL,
  `total_invoices` int DEFAULT NULL,
  `total_outstanding` decimal(38,2) DEFAULT NULL,
  `year` int NOT NULL,
  `association_id` bigint NOT NULL,
  `check_date` datetime(6) DEFAULT NULL,
  `checked_by` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `numbering_issues` text,
  `payment_issues` text,
  `pdf_path` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `invoices` (
  `amount` decimal(38,2) NOT NULL,
  `due_date` date DEFAULT NULL,
  `is_cancelled` bit(1) DEFAULT NULL,
  `is_paid` bit(1) DEFAULT NULL,
  `issue_date` date NOT NULL,
  `payment_date` date DEFAULT NULL,
  `activity_id` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `event_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_association_id` bigint DEFAULT NULL,
  `cancellation_reason` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `notes` text,
  `number` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKpa4f04a5qcpc80w6x1ry6v6o1` (`number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `issued_certificates` (
  `issue_date` date NOT NULL,
  `activity_id` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `event_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `issued_by` bigint DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `template_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `body_snapshot` text,
  `certificate_number` varchar(255) NOT NULL,
  `checksum` varchar(255) DEFAULT NULL,
  `pdf_path` varchar(255) DEFAULT NULL,
  `qr_code_data` varchar(255) DEFAULT NULL,
  `revoked_reason` varchar(255) DEFAULT NULL,
  `signatories` text,
  `status` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKlrxsf2xcqkr39mo4tj9ofjv86` (`association_id`,`certificate_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `journal_entries` (
  `date` date NOT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `transaction_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `reference_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `journal_entry_lines` (
  `credit` decimal(38,2) NOT NULL,
  `debit` decimal(38,2) NOT NULL,
  `account_id` bigint NOT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `journal_entry_id` bigint NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK3t3uhyexb3kw2t2xid4fjn9wx` (`account_id`),
  KEY `FKl0yqkqwya5s96hmxy9hq2c8yi` (`journal_entry_id`),
  CONSTRAINT `FK3t3uhyexb3kw2t2xid4fjn9wx` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`),
  CONSTRAINT `FKl0yqkqwya5s96hmxy9hq2c8yi` FOREIGN KEY (`journal_entry_id`) REFERENCES `journal_entries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `medical_certificates` (
  `expiry_date` date DEFAULT NULL,
  `issue_date` date DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `certificate_type` varchar(255) NOT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `issued_by` varchar(255) DEFAULT NULL,
  `medical_facility` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `member_consents` (
  `granted` bit(1) NOT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `granted_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint NOT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `consent_type` varchar(255) NOT NULL,
  `lawful_basis` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `members` (
  `birth_date` date DEFAULT NULL,
  `completeness_score` int DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `fiscal_code` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `member_category` varchar(255) DEFAULT NULL,
  `member_type` varchar(255) DEFAULT NULL,
  `membership_status` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `notifications` (
  `is_read` bit(1) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `related_entity_id` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `message` varchar(255) NOT NULL,
  `related_entity_type` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `payment_methods` (
  `fixed_commission` decimal(38,2) DEFAULT NULL,
  `has_commission` bit(1) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `percentage_commission` decimal(38,2) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `configuration` text,
  `name` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `resource_bookings` (
  `activity_id` bigint DEFAULT NULL,
  `approved_at` datetime(6) DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `booked_by` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `end_datetime` datetime(6) NOT NULL,
  `event_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `resource_id` bigint NOT NULL,
  `start_datetime` datetime(6) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `recurrence_rule` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `resources` (
  `capacity` int DEFAULT NULL,
  `cost_per_hour` decimal(38,2) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `requires_approval` bit(1) DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `image_path` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `sync_config` (
  `auto_sync_enabled` bit(1) DEFAULT NULL,
  `remote_port` int DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `last_sync_time` datetime(6) DEFAULT NULL,
  `remote_db_name` varchar(255) DEFAULT NULL,
  `remote_host` varchar(255) DEFAULT NULL,
  `remote_password` varchar(255) DEFAULT NULL,
  `remote_username` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `transactions` (
  `amount` decimal(38,2) NOT NULL,
  `commission_amount` decimal(38,2) DEFAULT NULL,
  `date` date NOT NULL,
  `is_renewal` bit(1) DEFAULT NULL,
  `is_verified` bit(1) DEFAULT NULL,
  `net_amount` decimal(38,2) DEFAULT NULL,
  `renewal_year` int DEFAULT NULL,
  `activity_id` bigint DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `category_id` bigint DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `event_id` bigint DEFAULT NULL,
  `fund_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `inventory_item_id` bigint DEFAULT NULL,
  `membership_id` bigint DEFAULT NULL,
  `project_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `verified_at` datetime(6) DEFAULT NULL,
  `verified_by` bigint DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `cost_center` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `quota_period` varchar(255) DEFAULT NULL,
  `receipt_path` varchar(255) DEFAULT NULL,
  `reference_id` varchar(255) DEFAULT NULL,
  `type` enum('EXPENSE','INCOME') NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKixnsw2xkm8tc7axcck1queu3k` (`verified_by`),
  CONSTRAINT `FKixnsw2xkm8tc7axcck1queu3k` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_associations` (
  `expiration_date` date DEFAULT NULL,
  `is_board_member` bit(1) DEFAULT NULL,
  `join_date` date DEFAULT NULL,
  `last_renewal_date` date DEFAULT NULL,
  `association_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `membership_card_number` varchar(255) DEFAULT NULL,
  `notes` text,
  `role` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKn3whn10uj9t88l4ulmfko73s9` (`association_id`),
  KEY `FKe2sq4an1sff4skl8nvqjk4lqb` (`user_id`),
  CONSTRAINT `FKe2sq4an1sff4skl8nvqjk4lqb` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `FKn3whn10uj9t88l4ulmfko73s9` FOREIGN KEY (`association_id`) REFERENCES `associations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `birth_date` date DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `updated_at` datetime(6) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `birth_place` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) NOT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `tax_code` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKj7x902dxnhswqjmycx9y6jq5c` (`tax_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `volunteer_expenses` (
  `amount` decimal(38,2) NOT NULL,
  `expense_date` date NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `shift_id` bigint DEFAULT NULL,
  `transaction_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `volunteer_id` bigint NOT NULL,
  `description` varchar(255) NOT NULL,
  `receipt_path` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `volunteer_shifts` (
  `hourly_value` decimal(38,2) DEFAULT NULL,
  `hours_worked` decimal(38,2) DEFAULT NULL,
  `activity_id` bigint DEFAULT NULL,
  `end_time` datetime(6) DEFAULT NULL,
  `event_id` bigint DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `start_time` datetime(6) DEFAULT NULL,
  `verified_at` datetime(6) DEFAULT NULL,
  `verified_by` bigint DEFAULT NULL,
  `volunteer_id` bigint DEFAULT NULL,
  `description` text,
  `role` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKbnx1wpgs1k35lqp598flf0nhc` (`verified_by`),
  CONSTRAINT `FKbnx1wpgs1k35lqp598flf0nhc` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `volunteers` (
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `member_id` bigint DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `availability` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `skills` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
